### ISSUE TITLE
python 3.10 not supported?

### ISSUE THREAD

**Issue by dolenec** [nielstron/ha_syncthru#4]
After updating HA to 2022.7.0 component do not loaded anymore...

reinstalling also do not help...
![slika](https://user-images.githubusercontent.com/16633222/177842778-2ba59ecd-7807-43b4-9d5e-cbe9ac7bc1d4.png)

Probably there is python issue...

**Comment by nielstron** [comment]
Just looking at the changelog of Python 3.10. I am taking a guess and assume the removal of distutils has broken stuff. I'll look into it

**Comment by dolenec** [comment]
Thank you..

**Comment by dolenec** [comment]
@nielstron Did you find problem?

**Comment by nielstron** [comment]
That sounds reasonable. The issue you are reporting is due to demjson deprecating, which is why I switched to demjson3 in the more recent versions of pysyncthru. I'll propose a version bump
